#!/bin/bash

#print out all tasksets within a directory that do not have results
#First argument is the directory containing tasksets, start and end are the
#starting and ending numbers of the tasksets

dir=$1
beg=$2
end=$3

output=""

for ((i=$beg; i<=$end; i++))
do
	#navigate to the result directory for current taskset
	mkdir -p $dir/taskset$i/result
	pushd $dir/taskset$i/result > /dev/null
	present_flag=0

	#compare filenames in result directory with expected pattern
	#NOTE: This does not detect half-finished results, it counts them as there
	for files in *
	do
		if [[ $files == task*_result.txt ]]; then
			present_flag=1
		fi
	done

	if [[ $present_flag == 0 ]]; then
		#echo "Taskset $i has no data!"
		output+="$i "
	fi

	popd > /dev/null
done

echo $output
