CC=/usr/bin/g++
FLAGS=-Wall -O2
#LOG=-DRT_GOMP_LOGGING=1
RG=-DRT_GOMP_USE_RELEASE_GUARD
#PL=-DPOLLING_LAUNCHER
PREEMPT=-DRT_PREEMPT_LOG=1 -DRT_GOMP_LOGGING=1
export PREEMPT
#OVERHEAD=-DCAL_OVERHEAD
#export OVERHEAD


all:
	make log
	make omp_utils
	make time_utils
	make exp
	make module

sem:
	make -C ../scripts all

log: sem
	make -C Logging all 
	
module:
	make -C ../modules all

omp_utils:
	$(CC) error.c -c $(FLAGS)
	$(CC) alloc.c -c $(FLAGS)
	$(CC) bar.c -c $(FLAGS)

time_utils:
	$(CC) time_utils.c -c $(FLAGS)

exp:
	make experiment
#	make exp_noprio
#	make exp_master_local

experiment: log omp_utils time_utils
	$(CC) $(LOG) $(PREEMPT) $(RG) $(PL) error.c alloc.o bar.o time_utils.o Logging/DataRecord.o experiment.cpp -O2 -o rt_experiment $(FLAGS) -lpthread -lrt

exp_noprio: log omp_utils time_utils
	$(CC) $(LOG) $(PREEMPT) $(RG) error.c alloc.o bar.o time_utils.o Logging/DataRecord.o exp_noprio.cpp -O2 -o rt_exp_noprio $(FLAGS) -lpthread -lrt

exp_master_local: log omp_utils time_utils
	$(CC) $(LOG) $(PREEMPT) $(RG) error.c alloc.o bar.o time_utils.o Logging/DataRecord.o exp_master_local.cpp -O2 -o rt_exp_master_local $(FLAGS) -lpthread -lrt

clean:
	make -C ../scripts clean
	make -C Logging clean
	make -C ../modules clean	
	rm -f *.o rt_experiment rt_exp_orig rt_exp_master_local rt_exp_noprio
